### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Mi-Pe** [boberle/vinted-downloader#5]
Apologies for an absolute noob question but how to use the photos fetching script? (the "download_full_size_images.sh")

Is it supposed to be run in a web browser or in system command prompt? I tried in Windows 10 command prompt and got this error:

"
'bash' is not recognized as an internal or external command,
operable program or batch file.
"

![-2024-mar-7-016](https://github.com/boberle/vinted-downloader/assets/73021367/e9516d74-06a3-4423-accb-46382b81f8e2)

I had previously put the "download_full_size_images.sh" file containing the script in the Downloads folder.

**Comment by boberle** [comment]
Hi Mi-Pe,

The `download_full_size_images.sh` bash script was a temporary solution from the issue #1 because the Python was not working at the time. You can still use it if you don't want to install Python (but you don't get the summary, but that's fine if you just want the photos). It works fine on Linux (and probably MacOS); it should be running on Windows if you activate bash on Windows but I've never tried that. The error shows that you haven't activated bash on Windows.

You can google how to run a bash script on Windows. I will try it in a VM and describe it to you, just give me one or two days.

Anyway, the recommended way to use the Vinted downloader is through the Python script (which requires that you have Python installed). I will put it on PyPI, so it will be easier to install.

I will try to do all that during this week-end.

**Comment by Mi-Pe** [comment]
Thank you for clarification. I mean, if it's going to be complicated and is gonna take a day or two off your life, please don't bother. Unless you really wanna do this for the prospective users as well. I will not use it, if it's gonna take me hours to figure out, install and run, since I have no programming experience.

**Comment by boberle** [comment]
Don't worry, it won't take me 2 days. It's just that I have other things planned... But a lot of people are asking me how to run it on Windows, so I will try to make a section in the Readme to help people to figure it out by themselves...

**Comment by boberle** [comment]
I've added a section in the README on how to install and run on Windows: https://github.com/boberle/vinted-downloader?tab=readme-ov-file#on-windows, with screenshots (on Windows 10, but it should be the same on Windows 11).

Basically, you just need to install Python (just download the installer and run it, like you would do for any other program).

Then open the Command Prompt (type "prompt" in the start menu) and install the Vinted downloader with:

```bash
pip install vinted-downloader
```

Then you can use it (I've created a command, so don't even have to type `python`)

```
vinted-downloader PRODUCT_URL
```

or:

```
vinted-downloader --seller -o DEST_DIR PRODUCT_URL
```

or with any other option described in the README (`vinted-downloader --help` for a list of options).

Let me know if you encounter a problem. Otherwise, feel free to close the issue.

**Comment by Mi-Pe** [comment]
Sorry for late response.
It still doesn't work for me.
I just want to download photos, so I tried to use the BASH script.
I still get the "'bash' is not recognized as an internal or external command, operable program or batch file." message, even though I had confirmed successful installation of Python.
I also updated the BASH script with Polish TLDs (altered the 18th and 33rd line) and successfully installed the main script, although with a warning:
![-2024-mar-15-013](https://github.com/boberle/vinted-downloader/assets/73021367/4a40baf4-6bc9-4e0e-aebb-2d2658e48a34)

**Comment by boberle** [comment]
Since you have installed Python, don't use the `bash` command, which won't work.

It's strange that the `vinted-downloader` command is not recognized.

Do you get the version of Python if you run `python --version` (or an error message)? If you do, can you run:

```bash
python -m vinted_downloader --all "URL"
```

**Comment by Mi-Pe** [comment]
I did get the Python version, no error there.
Your latest command works, it started downloading item info and pictures, along with pictures of "similar items" listed below the main item.
I could use this one, but since I just need the pictures of the main item, I'm wondering how to make the bash script work - maybe it would do the job faster.

**Comment by boberle** [comment]
If you just want the pictures of the main items, don't use any option (the `--all` options will download the pictures of all the items on the page, not just the main one).

So:

```
python -m vinted_downloader "URL"
```

You will just have 2 extra text files (`item.json` and `item_summary`), which you can delete.

`bash` is only available on some OS like Linux and MacOS (which are Unix-like OS), and not on Windows. You can use `bash` on Windows through the Windows Subsystem for Linux, but, basically, this requires you to install a Linux distribution inside Windows, which seems a bit overkill... To be fair, it should be possible to convert the bash script into a powershell script (the shell used by Windows), but unfortunately I don't know how to program in powershell.

If the 2 extra text files bother you, I can add an option to no write them, so you will just have the pictures. It's done in a few minutes, so just tell me.

**Comment by Mi-Pe** [comment]
They don't, I just wanted to skip the other items' pictures, so here we are. The text files are fine, I will delete them, I'm happy. Thank you for your help!
